#!/usr/bin/env bash
# cerbral-index.sh
# Generates ~/cerbral/INDEX.md — a human-readable, AI-readable summary of
# everything in your Cerbral brain. Always lives on your local disk, even
# after pruning, so Cerbral can always see what you have and know to
# fetch the full content from GitHub on demand.
#
# Run automatically by cerbral-mirror.sh after every sync.

set -uo pipefail
# NOTE: deliberately NOT using `set -e` — we want to be resilient to
# individual file-parse failures rather than aborting the whole index.

CERBRAL_HOME="${CERBRAL_HOME:-$HOME/cerbral}"
INDEX="$CERBRAL_HOME/INDEX.md"
BRAIN="$CERBRAL_HOME/brain"
KNOWLEDGE="$CERBRAL_HOME/knowledge"

REMOTE_URL="$(cd "$CERBRAL_HOME" 2>/dev/null && git config --get remote.origin.url 2>/dev/null || echo '(not configured)')"
BRANCH="$(cd "$CERBRAL_HOME" 2>/dev/null && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo main)"

# Convert ssh url to https web url for browsing.
WEB_URL="$REMOTE_URL"
case "$WEB_URL" in
  git@github.com:*)
    WEB_URL="https://github.com/${WEB_URL#git@github.com:}"
    WEB_URL="${WEB_URL%.git}"
    ;;
esac

# Extract the `description:` line from a markdown frontmatter block, if present.
# Always exits 0. Prints nothing if missing.
desc_of() {
  local f="$1"
  [ -f "$f" ] || return 0
  # Only look at the first 40 lines (frontmatter zone).
  head -n 40 "$f" 2>/dev/null | \
    grep -m1 '^description:' 2>/dev/null | \
    sed 's/^description: *//' | \
    head -c 200
}

# First non-empty, non-frontmatter line of a file.
first_line() {
  local f="$1"
  [ -f "$f" ] || return 0
  awk '
    BEGIN { infm = 0 }
    /^---$/ { infm = !infm; next }
    infm { next }
    NF { print; exit }
  ' "$f" 2>/dev/null | head -c 160
}

human_size() { du -sh "$1" 2>/dev/null | awk '{print $1}'; }

# Line count of a file, as a plain number. 0 if missing.
lc() { wc -l < "$1" 2>/dev/null | tr -d ' '; }

count_md() { find "$1" -type f -name '*.md' 2>/dev/null | wc -l | tr -d ' '; }

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Cerbral — Index"
  echo
  echo "_This file is an always-current summary of this user's Cerbral brain._"
  echo "_Generated by \`cerbral-index.sh\` after every mirror. Safe to read even when_"
  echo "_parts of the brain have been pruned locally — any file referenced here can_"
  echo "_be fetched from the GitHub repo below on demand._"
  echo
  echo "- **Last updated:** $(date -Iseconds)"
  echo "- **Local brain home:** \`$CERBRAL_HOME\`"
  echo "- **Remote (authoritative):** $WEB_URL  (branch \`$BRANCH\`)"
  echo "- **To fetch a file not present locally:**"
  echo "  \`\`\`bash"
  echo "  gh api repos/\$USER/cerbral-brain/contents/<path> --jq '.content' | base64 -d"
  echo "  curl -fsSL https://raw.githubusercontent.com/\$USER/cerbral-brain/$BRANCH/<path>"
  echo "  \`\`\`"
  echo

  if [ -d "$BRAIN" ]; then
    echo "## Brain"
    echo
    echo "- Total size: $(human_size "$BRAIN")"
    echo "- Skill categories: $(find "$BRAIN/skills" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l | tr -d ' ')"
    echo "- Skill files: $(count_md "$BRAIN/skills")"
    echo "- Memory files: $(count_md "$BRAIN/memories")"
    echo

    if [ -f "$BRAIN/SOUL.md" ]; then
      echo "### SOUL.md"
      echo
      echo '```'
      head -n 10 "$BRAIN/SOUL.md" 2>/dev/null
      echo '```'
      echo
      echo "_Full file: \`brain/SOUL.md\`. Size: $(human_size "$BRAIN/SOUL.md"), $(lc "$BRAIN/SOUL.md") lines._"
      echo
    fi

    if [ -d "$BRAIN/skills" ]; then
      echo "### Skills"
      echo
      echo "Found $(find "$BRAIN/skills" -type f -name 'SKILL.md' 2>/dev/null | wc -l | tr -d ' ') skills across $(find "$BRAIN/skills" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l | tr -d ' ') categories:"
      echo
      find "$BRAIN/skills" -type f -name 'SKILL.md' 2>/dev/null | sort > "$tmp"
      while IFS= read -r skill; do
        [ -f "$skill" ] || continue
        rel="${skill#$BRAIN/}"
        d="$(desc_of "$skill")"
        [ -z "$d" ] && d="$(first_line "$skill")"
        [ -z "$d" ] && d="(no description)"
        printf -- '- `%s` — %s\n' "$rel" "$d"
      done < "$tmp"
      echo
    fi

    if [ -d "$BRAIN/memories" ]; then
      echo "### Memories"
      echo
      find "$BRAIN/memories" -type f -name '*.md' -not -name '*.lock' 2>/dev/null | sort > "$tmp"
      while IFS= read -r mem; do
        [ -f "$mem" ] || continue
        rel="${mem#$BRAIN/}"
        fl="$(first_line "$mem")"
        [ -z "$fl" ] && fl="(empty)"
        printf -- '- `%s` (%s lines) — %s\n' "$rel" "$(lc "$mem")" "$fl"
      done < "$tmp"
      echo
    fi
  fi

  if [ -d "$KNOWLEDGE" ]; then
    echo "## Knowledge (user-authored, by domain)"
    echo
    find "$KNOWLEDGE" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | sort > "$tmp"
    while IFS= read -r domain; do
      [ -d "$domain" ] || continue
      name="$(basename "$domain")"
      cnt="$(count_md "$domain")"
      sz="$(human_size "$domain")"
      echo "### $name ($cnt files, $sz)"
      echo
      find "$domain" -type f -name '*.md' 2>/dev/null | sort | while IFS= read -r f; do
        [ -f "$f" ] || continue
        rel="${f#$KNOWLEDGE/}"
        fl="$(first_line "$f")"
        [ -z "$fl" ] && fl="(empty)"
        printf -- '- `%s` — %s\n' "$rel" "$fl"
      done
      echo
    done < "$tmp"
  fi

  echo "## Local disk posture"
  echo
  echo "- Free on \$HOME volume: $(df -h "$HOME" 2>/dev/null | awk 'NR==2 {print $4}')"
  if [ -d "$HOME/.hermes" ]; then
    echo "- \`~/.hermes/\` total size: $(human_size "$HOME/.hermes")"
    for sub in sessions sandboxes checkpoints audio_cache image_cache logs; do
      if [ -d "$HOME/.hermes/$sub" ]; then
        echo "  - \`$sub/\`: $(human_size "$HOME/.hermes/$sub") (ephemeral, pruneable via \`cerbral prune\`)"
      fi
    done
  fi
  echo
  echo "---"
  echo
  echo "_If content referenced in this index is missing locally, fetch it from the remote._"
  echo "_The remote repo is the authoritative brain; local \`~/cerbral/\` is a working cache._"
} > "$INDEX"

echo "index written: $INDEX ($(lc "$INDEX") lines)"
